update public.lectures set title = '다시 교회로 오는 3040', speaker = '김영선 목사', position = '목양 팀장', location = 'A101' where id = 'lec-d1-01';
update public.lectures set title = '소모임, 요즘 크리스천들이 교회에서 노는 이유', speaker = '차우병 목사', position = '소모임 담당', location = 'A102' where id = 'lec-d1-02';
update public.lectures set title = '목회철학을 풀어내는 최고의 방법, 의외로 행정과 재무입니다', speaker = '박승국 목사 / 김호태 장로', position = '행정 담당 / 재무 담당', location = 'A103' where id = 'lec-d1-03';
update public.lectures set title = '따로 또 같이, 네트워크 교회', speaker = '김종윤(이천만나), 박성욱(남양주만나), 엄태호(창원만나), 정모세(영종만나), 최호균(용인만나)', position = '네트워크 교회', location = 'A104' where id = 'lec-d1-04';
update public.lectures set title = '※목사님 출입금지※ 사모님 상담소', speaker = '최인숙 사모 & 김정화 사모', position = '사모님 상담', location = 'A105' where id = 'lec-d1-05';
update public.lectures set title = '만나IC 총괄 기획자가 말하는 목회 브랜딩의 시작', speaker = '김유나 집사', position = '브랜디렉터', location = 'A106' where id = 'lec-d1-06';
update public.lectures set title = '김병삼 목사님, 커피챗 가능하신가요?', speaker = '김병삼 목사 & 신학생', position = '신학생 한정', location = 'A107' where id = 'lec-d1-07';
update public.lectures set title = '나만의 목회철학을 그리는 시간', speaker = '참석자 3~4인씩 소그룹', position = '소그룹 워크숍', location = 'A108' where id = 'lec-d1-08';
update public.lectures set title = '인스타로 목회하는 방법', speaker = '김성경 목사', position = '커뮤니티 오브 니어', location = 'B101' where id = 'lec-d2-01';
update public.lectures set title = 'AI 간사님과 함께 사역하기', speaker = '박의성 목사', position = '교구행정 담당', location = 'B102' where id = 'lec-d2-02';
update public.lectures set title = '교회학교 부장님들이 알려주는 ''신앙 놀이터'' 설계법', speaker = '전준표 목사 / 교회학교 부장님들', position = '교회학교 총괄', location = 'B103' where id = 'lec-d2-03';
update public.lectures set title = '세살 신앙 여든간다! 가정과 아이가 함께 자라는 유치원, 사무엘 학교', speaker = '문지희 목사', position = '사무엘학교 교육', location = 'B104' where id = 'lec-d2-04';
update public.lectures set title = '상처 입은 청년부, 다시 공동체를 세울 수 있는가? : 불안과 고립의 시대, 청년사역의 본질과 회복', speaker = '이종현 목사', position = '청년부 팀장', location = 'B105' where id = 'lec-d2-05';
update public.lectures set title = '교회의 미래를 결정하는 시니어 사역', speaker = '임병천 목사', position = '시니어 사역 담당', location = 'B106' where id = 'lec-d2-06';
update public.lectures set title = '복지 사각지대를 비추는 나눔사역, 복지코디', speaker = '이용주 목사', position = '섬김국장', location = 'B107' where id = 'lec-d2-07';
update public.lectures set title = '평신도가 말하는 세상에 없던 평신도 사역', speaker = '이상한 장로 / 진오민 권사', position = 'BM 부장 / SOOM 위원장', location = 'B108' where id = 'lec-d2-08';
update public.lectures set title = '김병삼 목사님, 커피챗 가능하신가요?', speaker = '김병삼 목사 & 신학생', position = '신학생 한정', location = 'B109' where id = 'lec-d2-09';
update public.lectures set title = '다음시대의 사역을 그리는 시간', speaker = '참석자 3~4인씩 소그룹', position = '소그룹 워크숍', location = 'B110' where id = 'lec-d2-10';
update public.lectures set title = '변화산새벽기도회 기획노트 A~Z 전격공개', speaker = '이현규 목사', position = '예배기획 팀장', location = 'C101' where id = 'lec-d3-01';
update public.lectures set title = '와, 정말 핵심을 찔렀어! AI 예배 활용법', speaker = '김이삭 목사', position = '미디어 팀장', location = 'C102' where id = 'lec-d3-02';
update public.lectures set title = '찬양 인도, 이것만 알면 쉬워진다', speaker = '나요한 목사', position = '음악부 팀장', location = 'C103' where id = 'lec-d3-03';
update public.lectures set title = '귀에 꽂히는 설교 스피치', speaker = '김진 기자', position = '채널A 동아일보 기자', location = 'C104' where id = 'lec-d3-04';
update public.lectures set title = '교회 안에 스며든 예배 음악의 타락', speaker = '유은성 전도사', position = '찬양사역자', location = 'C105' where id = 'lec-d3-05';
update public.lectures set title = '한 끗 차이로 달라지는 설교, 탈고가 만듭니다.', speaker = '오예송 전도사', position = '출판/묵상 담당', location = 'C106' where id = 'lec-d3-06';
update public.lectures set title = '거울 앞에서 준비하는 예배, 코디도 예배다', speaker = '김진영 권사', position = '전 협성대 미술대학 교수', location = 'C107' where id = 'lec-d3-07';
update public.lectures set title = '장비 없어도 할 수 있는 교회 음향 실전 워크숍', speaker = '원영진 간사', position = '음향 간사', location = 'C108' where id = 'lec-d3-08';
update public.lectures set title = '24년차 영상 간사님이 알려주는 영상 제작 실전 워크숍', speaker = '석은충 간사', position = '영상 간사', location = 'C109' where id = 'lec-d3-09';
update public.lectures set title = '김병삼 목사님, 커피챗 가능하신가요?', speaker = '김병삼 목사 & 신학생', position = '신학생 한정', location = 'C110' where id = 'lec-d3-10';
update public.lectures set title = '예배의 중심을 그리는 시간', speaker = '참석자 3~4인씩 소그룹', position = '소그룹 워크숍', location = 'C111' where id = 'lec-d3-11';
